ims:
  - name: "telegram-bot-1234"  
    enable: true              
    adapter: "telegram"      
    config:                   
      token: "abcd"          


plugins:
  enable: []                 


web:
  host: "0.0.0.0"         
  port: 8080                
  secret_key: "rj231147"  


llms:
  api_backends:             
    
    - name: "deepseek-official"  
      adapter: "deepseek"        
      enable: true               
      config:                    
        api_key: "sk-b4702ba4c2334258826e614a8e62069c"  
        api_base: "https://api.deepseek.com/v1"
      models:                    
        - "deepseek-chat"
        - "deepseek-coder"
    


defaults:
  llm_model: deepseek-chat 

memory:
  persistence:                  
    type: file                 
    file:                      
      storage_dir: ./data/memory  
    redis:                     
      host: localhost          
      port: 6379              
      db: 0                   
  max_entries: 100            
  default_scope: member       
